name: Build and test (g++)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    CXX: g++

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build (gcc)
      run: make
    - name: Test (gcc)
      run: make test
    - name: Build (release, aggressive optimizations) (gcc)
      run: make RELEASE=true AGGRESSIVE_OPTIMIZE=true
    - name: Test (release, aggressive optimizations) (gcc)
      run: make test RELEASE=true AGGRESSIVE_OPTIMIZE=true
